# Generated by Django 3.2.9 on 2021-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500, verbose_name='project name')),
                ('name_content', models.CharField(max_length=500, verbose_name='content name')),
                ('resource', models.CharField(max_length=500)),
                ('id_format_content', models.PositiveIntegerField()),
                ('url', models.CharField(max_length=500)),
                ('success', models.IntegerField()),
                ('success_data_update', models.IntegerField()),
                ('acc_type', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
